### ISSUE TITLE
mp image

### ISSUE THREAD

**Issue by paulvi** [angelozerr/angular2-eclipse#15]
Would you change https://marketplace.eclipse.org/content/angular2-eclipse image 
to the one modified as on http://www.nodeclipse.org/updates/list

![](http://www.nodeclipse.org/img/list/Angular2-Eclipse.png)

So that v1 & v2 images differ a bit

**Comment by angelozerr** [comment]
@paulvi are you sure it's an official logo? https://angular.io/ seems using the same logo than I use for marketplace.

**Comment by micaelgallego** [comment]
The official Angular 2 logo is similar to Angular 1 logo but without grey border.
There are a lot of unofficial Angular 2 logos out there because they are too similar and I think nobody notes the difference ;)

**Comment by paulvi** [comment]
That is definitely not official. I need distinct image for AngulatJS and Angular2, as there are 2 different marketplace entries.

Similar for TypeScript, and image is needed that would be clear that is not related to previous TypeScript marketplace entries.
take a look http://www.nodeclipse.org/updates/list

@angelozerr Maybe you you own logo to put in image corner. Similar to GUI icon creation.

**Comment by angelozerr** [comment]
I prefer using official logo. If you know it, please tell me. Thanks!

I close this issue.
