### ISSUE TITLE
Disabling npm modules validation by default

### ISSUE THREAD

**Issue by kgidwani** [angelozerr/angular2-eclipse#18]
Hi,

The build by default also validates the npm modules. 
Can we remove the default validation of npm modules from build?

**Comment by angelozerr** [comment]
Build should use  tsconfig.json. Have you tried to exclude "node_modules" inside tsconfig.json. If you have problems,please share your project.

**Comment by angelozerr** [comment]
@kgidwani which validation do you speak? In typescript.java 1.1.0, I have removed WTP TypeScript Validator. Only TypeScript Builder witll be available.

**Comment by angelozerr** [comment]
None answer. I close this issue. Please reopen it if you have problems again.
