### ISSUE TITLE
Angular2 @Component/template syntax coloration 

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/angular2-eclipse#2]
Waiting for JSDT Editor improvement https://bugs.eclipse.org/bugs/show_bug.cgi?id=486961

**Comment by angelozerr** [comment]
Since TM4E is included inside angular2 eclipse, I will do this issue with Textmate (like VSCode does).

**Comment by angelozerr** [comment]
@Springrbua this issue is done. Here the result:

![image](https://cloud.githubusercontent.com/assets/1932211/25402350/b76fd2aa-29f8-11e7-9d62-cfe550d7e4ca.png)


See https://github.com/angelozerr/angular2-eclipse/wiki/New-and-Noteworthy-1.3.0#angular2-syntax-coloration for more information.

**Comment by Springrbua** [comment]
@angelozerr Looks pretty cool! Great work!
