### ISSUE TITLE
Creating new Angular2 Project does not work (at least on Mac)

### ISSUE THREAD

**Issue by hansprueller** [angelozerr/angular2-eclipse#20]
I am running Eclipse Neon on my MacBookPro with macOS el capitan.

npm and node are basically installed, i already have successfully implemented the "angular 2 hello world" tutorial project on the command line and could run the ng2 app.

now I tried to make an ng2 project in eclipse, using the angular2-eclipse feature.

after i installed it (without any error message), and try to create a new project by using the new-project wizard for a "new Angular2 project"

the project is created EMPY and console shows the following error(s):
==

/Users/hansp/.profile: line 4: .bashrc: No such file or directory
/bin/bash: line 1: ng: command not found

**Comment by angelozerr** [comment]
Have you do:

`npm install -g angular-cli`

Close your eclipse, restart it.

See https://github.com/angelozerr/angular2-eclipse/wiki/AngularCLI ?

**Comment by hansprueller** [comment]
Ah sorry, did only install the eclipse feature and did not know that installing angular-cli was a prerequisite (the only prerequisite I know was that eclipe neon is needed).

tried it as you suggested and now it works like a charm, thank you.

hans

**Comment by angelozerr** [comment]
When I will find time, I will try to avoid doing that, just find time.....

**Comment by dejanmr** [comment]
I have similar problem. Platform: Eclipse Neon.1 (4.6.1), Ubuntu 16.04.1 LTS

the project is created EMPTY and console shows the following error(s):
<terminated> ng init
/bin/bash: line 1: ng: command not found

I have run npm install -g angular-cli before.

Running command from "ng init" from terminal works fine. Samples from https://angular.io/docs/ts/latest/tutorial/ work fine (outside eclipse)

Thanks.

**Comment by ahaan729** [comment]
Any idea what is supposed to be exported to a war if I want to deploy an application to a prod. server?

**Comment by amir2260** [comment]
i have same problem, eclipse oxygen on macos
