### ISSUE TITLE
ng is not recognized as internal or external command - windows

### ISSUE THREAD

**Issue by LucDepauw** [angelozerr/angular2-eclipse#21]
Hi,

I've installed eclipse neon and added the 4 plugins from the 1.0.0 download site.
The ng command is not recognized.
I used the build-in nodejs and also tried with an external  portable nodejs with angular installed no luck. (the portable nodejs works fine in windows cmd)
Running on windows 8.

Regards
Luc

**Comment by angelozerr** [comment]
Same issue than https://github.com/angelozerr/angular2-eclipse/issues/20 ?

**Comment by LucDepauw** [comment]
Root cause, nodejs is not on the path, don't know how you push the included nodejs on the terminal path or the external but both are not working. Btw I'm not admin on the windows system that's why I use portable nodejs, on the windows cmd I can install angular-cli and create projects.

**Comment by angelozerr** [comment]
@LucDepauw is this issue https://github.com/angelozerr/angular2-eclipse/issues/22 could fix your problem?

**Comment by LucDepauw** [comment]
Probably #22 will fix the issue, workaround not test yet, create a bat file with adjusted win path that includes path to nodjs and execute startup of eclipse...

**Comment by angelozerr** [comment]
@LucDepauw please install 1.2.0-SNAPSHOT. I hav eimplemented https://github.com/angelozerr/angular2-eclipse/issues/22

**Comment by LucDepauw** [comment]
Hi, Installed on a fresh neon, installed from download site, seems to work ok with supplied win nodejs. I did have to install angular manually which was not clear in issue #22 with command  'npm install -g @angular/cli' after that I could create a project in Eclipse. Have some error popups when doing ng serve, probably the launching of the webbrowser is out-of-sync with starting the webserver, but the app works fine after manually connect to http://localhost:4200 in chrome browser.

**Comment by angelozerr** [comment]
> seems to work ok with supplied win nodejs

Very cool news.

> which was not clear in issue #22 with command 'npm install -g @angular/cli' 

Perhaps you wish to use a custom ng file like https://github.com/angelozerr/angular2-eclipse/issues/36
If it that I must improve this issue.

> Have some error popups when doing ng serve, 

Could create an issue with that?

Can I close this issue?

**Comment by LucDepauw** [comment]
Yes, you can close issue. Thx for the support.
