### ISSUE TITLE
Create additional runtime configurations

### ISSUE THREAD

**Issue by PMJMendes** [angelozerr/angular2-eclipse#23]
Just as Run As ng build and Run As ng serve execute the respective commands, it would be nice to have a run configuration that would invoke ng test.

It would also be nice if all three of these commands were added to the Debug As menu, and have the Eclipse debugger connect to the running node.js instance.

Lastly, but perhaps requiring massive amounts of additional work, it would be nice if ng test were also added to the Coverage As menu.

**Comment by angelozerr** [comment]
>  it would be nice to have a run configuration that would invoke ng test.

Yes sure.

> It would also be nice if all three of these commands were added to the Debug As menu, and have the Eclipse debugger connect to the running node.js instance.

To support debugging we must wait that JSDT support node.js debugging. See https://github.com/angelozerr/typescript.java/issues/2 for more information.

> Lastly, but perhaps requiring massive amounts of additional work, it would be nice if ng test were also added to the Coverage As menu.

Could you give me more info about that (a screenshot about what you wish to have)?

**Comment by PMJMendes** [comment]
Regarding the Coverage As, basically, for Java projects, I use EclEmma. It runs the unit tests, then modifies the source editor to display each line in green (executed), red (not executed) or yellow (executed some branches, but others missing). I don't think anything like that exists for JavaScript/TypeScript, which is why I think it's a massive amount of work. Things like that may or may not eventually end up in JSDT as well...

**Comment by angelozerr** [comment]
Ok I see the idea. Indeed I think it's a big work. Could you create an issue with your idea please. Thanks

**Comment by PMJMendes** [comment]
Done. Issue 27. :)

**Comment by angelozerr** [comment]
@PMJMendes I have added ng test and e2e with launch. 

I have started too to implement ng editor (ope angular-cli.json)  and you can too lanch ng serve, test e2e, build with action (see on the top of the the editor): 

![ngeditor](https://cloud.githubusercontent.com/assets/1932211/19393810/9ea5eca0-9236-11e6-928b-c20fd9185289.png)

For the moemnt name version can be managed. Please suggest your idea at https://github.com/angelozerr/angular2-eclipse/issues/26 if you need improvement.

I close this issue.
