### ISSUE TITLE
No tab group defined for launch configuration type angularCLILaunchConfigurationType

### ISSUE THREAD

**Issue by PMJMendes** [angelozerr/angular2-eclipse#24]
The above error message appears when attempting to create additional run configurations by hand under the Angular CLI heading in Eclipse's run configuration manager.

**Comment by angelozerr** [comment]
Yes sure. It's because I have not implemented UI for Angular CLI launch.

Please suggest me which UI you wish to have

**Comment by PMJMendes** [comment]
I'm not sure. A simple "angular-CLI arguments" text box is probably enough, but off-hand, there may be other possible use cases I'm not seeing...
