### ISSUE TITLE
Duplicate template id's

### ISSUE THREAD

**Issue by PerBalling** [angelozerr/angular2-eclipse#28]
Ver. 1.1.0
In the **.log file** for eclipse I get these warnings:
!ENTRY org.eclipse.jface.text 2 0 2016-10-27 14:56:29.421
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.number'

!ENTRY org.eclipse.jface.text 2 0 2016-10-27 14:56:29.429
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.round'

!ENTRY org.eclipse.jface.text 2 0 2016-10-27 14:56:29.449
!MESSAGE Duplicate template id: 'ts.eclipse.ide.jsdt.ui.templates.react.ptelr'

!ENTRY org.eclipse.jface.text 2 0 2016-10-27 14:56:29.456
!MESSAGE Duplicate template id: 'ts.eclipse.ide.jsdt.ui.templates.react.ptir'

**Comment by angelozerr** [comment]
@PerBalling I have fixed warn for React ts.eclipse.ide.jsdt.ui.templates.react.ptelr and ts.eclipse.ide.jsdt.ui.templates.react.ptir. For the other, the problem comes from WTP. Please create a bugzilla to Eclipse with this problem. Thanks!

**Comment by PerBalling** [comment]
Thank you. _Great plugin you have built_ **:-)**

**Comment by mondjunge** [comment]
Workaround for people like me:
If you do not use XPath in any way, you can go to "Window -> Preferences -> XPath -> XPath Templates", select and remove all the templates. Warnings will be gone.
It could be wise to export them beforehand to a safe place to import them later if you need them.
Cheers.
