### ISSUE TITLE
Refactoring Support

### ISSUE THREAD

**Issue by Bernd0** [angelozerr/angular2-eclipse#29]
Hi,

I'm trying to refactor my code in Eclipse.

When I rename a class, the new name is not reflected project wide. e.g. the class name in the corresponding module is still the old one.
I have the same problem, when I moving a file. The corresponding path references are not updated.

Is refactoring not supported? or I'm doing something wrong?

Cheers,
Bernd

**Comment by angelozerr** [comment]
It's not supported for the moment. I 'must finsh my work. See https://github.com/angelozerr/typescript.java/issues/28

**Comment by Bernd0** [comment]
Do you plan it to finish in near future? Or is it a feature you will support in long term?

**Comment by angelozerr** [comment]
I must finish my work with "compile on save" and after I would like to finish it. Hope I will implement it this month.

**Comment by Bernd0** [comment]
OK, thank you.
