### ISSUE TITLE
Integrates angular2 language service

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/angular2-eclipse#30]
Integrates https://github.com/angular/angular/tree/master/modules/%40angular/language-service

**Comment by angelozerr** [comment]
It works with TypeScript but not for HTML file. We need to wait for TypeScript/Angular work, see https://github.com/angular/vscode-ng-language-service/issues/43#issuecomment-299408716

**Comment by Springrbua** [comment]
@angelozerr [This PR](https://github.com/angular/angular/pull/16417) should be the one you are waiting for. It just made its way into the [4.2.0-beta.0](https://github.com/angular/angular/blob/master/CHANGELOG.md#420-beta0-2017-05-04) (see the last entry in `features`)

**Comment by angelozerr** [comment]
@Springrbua Angular Language Service have implemented the getExternaFiles() but not TypeScript. Now we must wait for TypeScropt work.

**Comment by angelozerr** [comment]
Here a demo with completion, hover, validation, hyperlink inside HTML file:

![htmlangulardemo](https://user-images.githubusercontent.com/1932211/27633199-850f57a8-5bfe-11e7-8472-b0c9f4935472.gif)
