### ISSUE TITLE
Options when generating a new Project

### ISSUE THREAD

**Issue by Springrbua** [angelozerr/angular2-eclipse#31]
Angular-CLI supports a few options, when generating a new project.
It would be cool to be able to use them in the Project-Generation-Wizard..
Following options are available (copied from "ng help"):
```
  --dry-run (Boolean) (Default: false)
    aliases: -d
  --verbose (Boolean) (Default: false)
    aliases: -v
  --link-cli (Boolean) (Default: false)
    aliases: -lc
  --skip-npm (Boolean) (Default: false)
    aliases: -sn
  --skip-git (Boolean) (Default: false)
    aliases: -sg
  --skip-tests (Boolean) (Default: false)
    aliases: -st
  --skip-commit (Boolean) (Default: false)
    aliases: -sc
  --directory (String)                   // Already supported by choosing project-location?
    aliases: -dir <value
  --source-dir (String) (Default: src)
    aliases: -sd <value>
  --style (String) (Default: css)
  --prefix (String) (Default: app) 
    aliases: -p <value>
  --mobile (Boolean) (Default: false)            // Disabled temporarily
  --routing (Boolean) (Default: false)
  --inline-style (Boolean) (Default: false)
    aliases: -is
  --inline-template (Boolean) (Default: false)
    aliases: -it
```

The most important ones (for me) are the following:
- skip-tests: No ".spec.ts"-Files generated
- style: Lets you specify the Style-Type (CSS, SCSS, SASS, LESS)
- prefix: Lets you specify the prefix for Components, Directives, etc.

**Comment by angelozerr** [comment]
Is there any change to have a PR with wizard page which contains thoses options?

**Comment by Springrbua** [comment]
I am planing to add this Options to the New-Project WizardPage, just like I did with New Module Wizard Page, if thats okay.
IF there are too many options, I might add another WizardPage...

**Comment by angelozerr** [comment]
> IF there are too many options, I might add another WizardPage...

IMHO, I think we should have 2 pages:

 * a page with requiered fields (the project name) like today. And add in this page the angular-cli version.
 * a second page with optional parameters. Those optional parameters could be dynamic according the angular-cli version. The idea is to execute ng help with the given angular-cli (to retrieve those options) and generate an UI (a checkbox if it's a boolean, etc). But perhaps we could start with a simply mean and hard coded the optional fields.

**Comment by Springrbua** [comment]
> a second page with optional parameters.

A second page sounds good. Do you think the (future) optional parameters for the "generate" commands should be on a second page to?

> Those optional parameters could be dynamic according the angular-cli version. The idea is to execute ng help with the given angular-cli (to retrieve those options) and generate an UI (a checkbox if it's a boolean, etc). But perhaps we could start with a simply mean and hard coded the optional fields.

The installed angular-cli version could really cause some problems.
In the case of the New-Project-Wizard, we have the possibility to consume the "ng help" command (as long as they don't change the structure of the answer).
However, the help of the "generate" command shows only a few general params (like "dry-run").
Other, blueprint specific, parameters aren't documented (on the Github page they are also a bit hidden and  can be found [here](https://github.com/angular/angular-cli/tree/master/docs/documentation/generate)).

For now maybe hardcoding the optional fields will do (lets say we define a min. and max. cli-version for each option).
However it could cause problems, if they remove an option, as the plugin might be older then the cli-version...

**Comment by angelozerr** [comment]
> Do you think the (future) optional parameters for the "generate" commands should be on a second page to?

I think we could keep the optional options in the same page since this page shows fews fields. We could hide thoses fields by default and display a label like "Optional parameters". When user click on "Optional parameters", it expands and shows optional parameters.

> For now maybe hardcoding the optional fields will do

Agree with you. It should be cool if we could comment each field (available since version X)

**Comment by Springrbua** [comment]
@angelozerr I just tryed to use unknown parameters, when generating a new project and saw, that Angular-CLI just brings a warning and ignores the parameter.  
So I think it is not really neccessary to store the Min-CLI-Version required for a parameter, or what do you think?

**Comment by angelozerr** [comment]
> So I think it is not really neccessary to store the Min-CLI-Version required for a parameter, or what do you think

I think it should be more cleaner to show in the UI wizard page just the available parameters for an angular cli version. But for the moment don't loose our time with that, but I think it should be cool if we could just comment before the declaration of the field "avilable since $version. In the future we could use those comments to improve the UI and show only available parameters.

**Comment by Springrbua** [comment]
Yea you are right, it's definitely cleaner, but not required for the moment.  
I am almost odne with this, the project generation using all the different parameters, seems to work.
I only need to rearrange the Widgets on the WizarPage, then I will commit the changes.  

For the currently available parameters I would prefer to say that beta 25 or later is required, instead of looking through the whole Angular-CLI history, to perfectly support versions older then beta 25 ("skip-tests" for example is availlable since beta 25).
