### ISSUE TITLE
Support for ngModule

### ISSUE THREAD

**Issue by Springrbua** [angelozerr/angular2-eclipse#32]
Angular-CLI has a command for module-generation ("ng g module moduleName").
Using this command, it is possible to create a "normal" module, as well as a "routing" module ("--routing").
It would be cool, if the plugin supports generation for modules and routes, using a Wizard.

**Comment by angelozerr** [comment]
@Springrbua I'm sorry, I'm very busy with other topics like tslint, angular2 language service (to have angular2, tslint validation for @Component/template etc).

Thanks a lot with your contribution.

Could you add a screenshot with a little explnation at https://github.com/angelozerr/angular2-eclipse/wiki/New-and-Noteworthy-1.2.0 like https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.2.0

Thanks!

Can we close this issue?

**Comment by Springrbua** [comment]
I will make a screenshot as soon as possible.
The second point of the Issue is still open (choose module when generating a Component/Module7Directive etc.)
However I am not (yet) able to do that, as I don't know how to search for existing Moudles...
But we could create a new Issue for that...

**Comment by angelozerr** [comment]
> The second point of the Issue is still open (choose module when generating a Component/Module7Directive etc.)

The hardest feature:)

> However I am not (yet) able to do that, as I don't know how to search for existing Moudles...

I think we should use tsserver for that. TypeScript 2.2 will provide "plugin" feature to extends TypeScript completion, validation, etc. And Angular guys are implementing a plugin for Angular2 that I'm integrating (I can have completion, validation, hover, etc inside @Component/template (see https://github.com/angelozerr/angular2-eclipse/issues/30)) a very great feature (and more I'm working too to have HTML syntax coloration inside @Component/template (see https://github.com/angelozerr/angular2-eclipse/issues/2)).

So once Angular2 language service plugin will be integrated, we could study how to develop a TS 2.2 plugin to existing modules or even create a new issues like https://github.com/angular/angular/search?q=%5B%40angular%2Flanguage-service%5D+&type=Issues&utf8=%E2%9C%93

> But we could create a new Issue for that...

Yes please and after please close this issue.

**Comment by Springrbua** [comment]
@angelozerr How can I edit the wiki page? Do I need some special rights for that?

**Comment by angelozerr** [comment]
@Springrbua do you want to become a contributor?

**Comment by Springrbua** [comment]
Well, I would like to update the wikipage, as you said in the first comment and right now I can't...

However, I preffer to work on my fork, as I am pretty new to Eclipse Plugin-Development (started this week) and I would like to keep your repo cleen and stable :)

**Comment by angelozerr** [comment]
> Well, I would like to update the wikipage, as you said in the first comment, and right now I can't...

You should now edit the wiki. For the image, try to clone the wiki and add the images. Otherwise, don't loose your time with that, I will do the screenshot.

> However, I preffer to work on my fork, as I am pretty new to Eclipse Plugin-Development (started this week) and I would like to keep your repo cleen and stable :)

I understand. Very impressive if you are neebie with eclipse plugin dev!

**Comment by Springrbua** [comment]
Well I actually only searched for "Component" or "Directive". Then I only needed to copy the existing code and replace "Component" with "Module" :)

I'll update the Wiki-Page as soon as possible. However, I am a bit busy today, so I might update it tomorrow...

**Comment by Springrbua** [comment]
@angelozerr I edited the wikipage.
Screenshots are still missing, could you please add them, if it is not too much work?
Thanks

**Comment by angelozerr** [comment]
Thanks @Springrbua I will do it.
