### ISSUE TITLE
Support for angular-cli generated projects out of the box

### ISSUE THREAD

**Issue by micaelgallego** [angelozerr/angular2-eclipse#4]
As [angular-cli](https://github.com/angular/angular-cli) is the official tool to generate boilerplate for angular 2 projects, I think it is good to have support for this tool out of the box.

As per documentation, it is recommended to install angular-cli globally with `npm install -g angular-cli` to use commands directly in the command line. The following commands are some of the most important:
* `ng new PROJECT_NAME`: Creates a new project.
* `ng serve`: Start a web server with integrated TS compiler and browser auto-reload on save.
* `ng build`: Generates distribution artifacts.

I think it will be good if angular2-eclipse have direct short-cuts to these commands and show its output.

In the future it can be considered to allow execute jasmine tests directly in a browser integrated in eclipse, show results, etc...

What do you think?

**Comment by angelozerr** [comment]
>  I think it is good to have support for this tool out of the box.

Yes sure.

> I think it will be good if angular2-eclipse have direct short-cuts to these commands and show its output.

....

In the future it can be considered to allow execute jasmine tests directly in a browser integrated in eclipse, show results, etc...

You mean to have an "ng" launch configuration type like I have doen for protractor https://github.com/angelozerr/angularjs-eclipse/wiki/Protractor

**Comment by micaelgallego** [comment]
> You mean to have an "ng" launch configuration type like I have done for protractor https://github.com/angelozerr/angularjs-eclipse/wiki/Protractor ?

Yes, something like that will be very cool. I don't know how difficult can be port this functionality to Angular 2, but if you focus initially in angular-cli tool, maybe it is easier because the project structure (and dependencies) are well known.

I focused in angular-cli because I think that support every angular2 seed project out there can be very complicated and angular-cli is the official one.

**Comment by angelozerr** [comment]
@micaelgallego do you think it could be interested to have Wizard (New Angular2 Project, New Component, etc) which calls angular2-cli ?

**Comment by paulvi** [comment]
BTW, New user may not know about having to install `angular-cli`. Some warning should be.

Nodeclipse has similar idea by using express generator
https://github.com/Nodeclipse/nodeclipse-1/blob/master/org.nodeclipse.ui/src/org/nodeclipse/ui/wizards/ExpressProjectWizard.java#L104

**Comment by angelozerr** [comment]
> BTW, New user may not know about having to install angular-cli. Some warning should be.

IMHO I think IDE should work without installing nothing. It's the idea that I have followed with typescript.java :

 * no need to install node.js (by providing embedded node.js)
 * no need to install TypeScript (by providing a TypeScript bundle)

BUT user can override the embedded node.js and default TypeScript if they wish.

I would like to follow the  same idea. When user will install Angular2 Eclipse it will provide a default angular2-cli (that user will able to override if he wishes). The install of default angular2-cli could be a feature update site (is user doesn't want to install it and in this case a warning should be like you have mentionned @paulvi )

**Comment by micaelgallego** [comment]
+1
If plugin includes all necessary software it is easier for newbies. For more advanced users, as you suggested, I think will be good to have the possibility to not install embebed node.js and angular-cli

**Comment by angelozerr** [comment]
@micaelgallego do you think it's better to have an Angular2 Console or an Angular2 Wizerd?

**Comment by micaelgallego** [comment]
It depends on the concrete task. But as today angular-cli is in alpha and change every day. A console is more robust and adaptative to changes. In the future, when tools are more mature, maybe several wizards can be implemented. What do you think?

**Comment by angelozerr** [comment]
Are you sure that "ng init", "ng g component my-new-component" will change?

I don't know if it's easy to implement Console, like Bower, NPM console.

**Comment by micaelgallego** [comment]
You are right, these basic commands are very stable. If angular2-eclipse offers wizards it will be amazing, but maybe command parameters can change and it will be more work to maintain plugin updated. There is other important aspect to take account. The command `ng serve` provides useful information in the console and it is always executing (to offer incremental compilation). The wizard is not very suitable in this case.

A console is not very eclipse-friendly, but it can be easier to implement reusing other eclipse plugins. In a first version console can be very useful. In following versions, new wizards can be implemented.

What do you think?

**Comment by angelozerr** [comment]
@micaelgallego @paulvi I have studied how we could integrate angular-cli with Eclipse : 

 * with wizard
 * with terminal shell.

I have commited some work for having a "New Angular2 Project" wizard but it doesn't work now.

I have studied terminal shell which is integrated with Eclipse. The cool thing is that we can extend and I have implemented a "Local Terminal (Interpreter)" where the idea is to interpret commands and refresh the workspace.

Here a demo with "new new" command (once ng new is finished the interpreter creates an Eclipse Project and open the generated package.json):

![animation](https://cloud.githubusercontent.com/assets/1932211/16161649/fe131eb2-34ce-11e6-94c2-56fc160041fe.gif)

Do you like it?

My idea with command interpreter is to provide an extension point to add other interepter. Here a sample with cd, and npm install:

![unnamed](https://cloud.githubusercontent.com/assets/1932211/16161771/a6efa168-34cf-11e6-88c4-e5e0f3c04ebb.gif)

For your information, I have created a bug for Terminal Eclipse with my idea at https://bugs.eclipse.org/bugs/show_bug.cgi?id=496109

**Comment by micaelgallego** [comment]
Hi @angelozerr, I think the approach of listening terminal is a good idea. It is good because all documentation of angular-cli can be applied "as is" but you can show results of commands (that is, files generated or modified) in the context of eclipse project explorer.

Good job!

**Comment by angelozerr** [comment]
@micaelgallego I have commited my work, but it exists again some bugs. (ex: the created project .project is not valid, I don't know why for the momement).

But is it possible for you to test if Local Terminal (Interpreter) is working for you. (ex: try the cd command which should select your project explorer).

I have Windows and it works but I don't know if it will work with other OS (@pascalleclercq could you test with your Mac OS please, thanks!)

**Comment by paulvi** [comment]
Looking again at https://bugs.eclipse.org/bugs/show_bug.cgi?id=447206

Is there actually bash script for angular completion? Like the exist for git

**Comment by angelozerr** [comment]
> Is there actually bash script for angular completion? Like the exist for git

It seems angular cli support that https://github.com/angular/angular-cli#commands-autocompletion

but I with Windows OS, I don't know how to do that (never used gitbash).

**Comment by angelozerr** [comment]
@micaelgallego I have finished my work about this (big) issue. Now you can consume [angular-cli](AngularCLI):

 * [With Terminal](https://github.com/angelozerr/angular2-eclipse/wiki/ngTerminal)
 * [With Wizards](https://github.com/angelozerr/angular2-eclipse/wiki/ngWizards)
 * [With Launches](https://github.com/angelozerr/angular2-eclipse/wiki/ngLaunches)

I think we could improve wizards for instance to add advanced parameters (for the moment just the name is available), add preferences for ng server, etc. But I don't know if it is very important.

Please create new issues if you need some improvement of if you find bugs.

Thanks!
