### ISSUE TITLE
Options when generating new Angular Blueprints

### ISSUE THREAD

**Issue by Springrbua** [angelozerr/angular2-eclipse#41]
When you generate a Blueprint (Component, Directive etc.) using Angular-CLI you can specify different parameters.  
This parameters affect the generated files and folders.  
It would be cool, if we could set this parameters inside the Wizards.

**Comment by angelozerr** [comment]
@Springrbua I think we can close this issue, no?

**Comment by Springrbua** [comment]
@angelozerr I still need to add the tooltip. But after that it can be closed.

**Comment by Springrbua** [comment]
@angelozerr I guess we should close this issue and create a new one regarding tooltips, as they don't have a too high priority right now. What do you say?

**Comment by angelozerr** [comment]
yes sure.
