### ISSUE TITLE
Endless loop when generating an already existing element

### ISSUE THREAD

**Issue by Springrbua** [angelozerr/angular2-eclipse#43]
If you try to generate an Angular element (Component, Directive etc.) which already exists inside the selected directory, Angular-CLI checks, if the execution changes anything.  
If the generated files are different, then the existing file, Angular-CLI asks, if you want to overwrite the existing files.  
The plugin does not take care about this "question" and so it does not input a valid value (Y,N,D or H).
The result is an endless loop with the following output:  
```
Path-To-Project\src\app>ng generate component core --prefix app --spec false --flat false
installing component
? Overwrite src\app\core\core\core.component.ts? (Yndh) [56D[56C[1000D[K?  
Overwrite src\app\core\core\core.component.ts? (Yndh) e[57D[57C[1000D[K?  
Overwrite src\app\core\core\core.component.ts? (Yndh) ex[58D[58C[1000D[K?  
Overwrite src\app\core\core\core.component.ts? (Yndh) exi[59D[59C[1000D[K?  
Overwrite src\app\core\core\core.component.ts? (Yndh) exit[60D[60C[1000D[K?  
Overwrite src\app\core\core\core.component.ts? (Yndh) 
>> Please enter a valid command[1A[31D[56C[1B[1000D[K[1A[1000D[K? Overwrite src\app\core\core\core.component.ts? (Yndh) e[57D[57C[1000D[K? Overwrite src\app\core\core\core.component.ts? (Yndh) ex[58D[58C[1000D[K? Overwrite src\app\core\core\core.component.ts? (Yndh) exi[59D[59C[1000D[K? Overwrite src\app\core\core\core.component.ts? (Yndh) exit[60D[60C[1000D[K? Overwrite src\app\core\core\core.component.ts? (Yndh) 
```  
This goes on until you terminate the process using the red button in eclipse.  
Possible solutions:  

1. Check if the generated files already exist. If they already exist, show an error and disable the "finish" button.

2. Take care about this result and let the user input a value in the console.  

I personaly would preffer the first solution. If the generated files already exist, the user should delete them manually first and then generate them again.

**Comment by angelozerr** [comment]
@Springrbua could you tell me if it's ok with terminal please.

**Comment by Springrbua** [comment]
Works prefectly, thanks!
