### ISSUE TITLE
Show generated files in blueprint Wizards

### ISSUE THREAD

**Issue by Springrbua** [angelozerr/angular2-eclipse#44]
In the blueprint Wizards (Component, Directive etc.) it would be nice, if we know, which files would be generated.  
The gererated files and folders depend on the generated element and the parameters.  
For example a Component named "header", generated with "-- spec false" would result in following files:  
```
header\header.component.ts  
header\header.component.css  
header\header.component.html
```  
while generating it with "--inline-template" and "--inline-style" would result in following files:  
```
header\header.component.ts  
header\header.component.spec.ts
```  
You also need to take care about the app-defaults (set in the angular-cli.json). For example you could set the style-extension there, so that `header.component.css` might become `header.component.scss`.  
This feature could also solve #43.

**Comment by angelozerr** [comment]
@Springrbua I reopen this issue since normalize is not supported.

**Comment by Springrbua** [comment]
@angelozerr Perfect! I just wanted to reopen it myself, but wasn't able to do that.
