### ISSUE TITLE
Syntax coloring HTML not working

### ISSUE THREAD

**Issue by bashoogzaad** [angelozerr/angular2-eclipse#48]
In Eclipse Preferences:

JavaScript -> TypeScript -> Angular2 -> HTML -> Editor -> Syntax Coloring throws an error
After clicking it again, it opens but the syntax coloring can not be changed.

**Comment by bashoogzaad** [comment]
Thank you very much, will test that!

**Comment by angelozerr** [comment]
Thanks to have reporting this issue. You must wait for that job which build angular2 eclipse finish in order to install 1.2.0-SNAPSHOT
