### ISSUE TITLE
Breaking changes in Angular-CLI (Beta 32)

### ISSUE THREAD

**Issue by Springrbua** [angelozerr/angular2-eclipse#49]
Angular-CLI beta 32 introduces a few breaking changes, which will affect the plugin.  
The breaking changes are listet in the [changelog](https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#breaking-changes).  
Following changes should affect the plugin:  
- The configuration file angular-cli.json has been renamed to .angular-cli.json  
- Generating a module with routing will no longer generate an associated component.  
- Removing the ng init & ng update commands because their current implementation causes more problems than it solves.  

Especially the renamed config and the removed commands will cause problems.

**Comment by angelozerr** [comment]
Thank @Springrbua for this info. I will try Angular-CLI beta 32.

I think we should support only this version upon cli is released, in other words, the open of  angular-cli.json will not work, and only.angular-json will work. Are you OK?

**Comment by Springrbua** [comment]
@angelozerr I tryed to create a new Angular-CLI project, and the new command say: "Directory already exists".  
I guess we need to find a way to execute the ng new command and then "import" the created irectory as a project...  
Do you think thats possible?

**Comment by angelozerr** [comment]
>  I tryed to create a new Angular-CLI project, and the new command say: "Directory already exists".

Please retry.

**Comment by kevindeuel** [comment]
Hi, I am using Eclipse Neon to create a new Angular 2 project and get the ng init issue. Is this something we have to manually adjust on our local files or is there an update to the Eclipse plugin?

**Comment by angelozerr** [comment]
Use 1.2.0-SNAPSHOT update site https://github.com/angelozerr/angular2-eclipse/wiki/Installation-Update-Site

1.2.0 will be soon released.

**Comment by angelozerr** [comment]
@Springrbua I think we can close this issue, no?

**Comment by kevindeuel** [comment]
@angelozerr Thank you!

**Comment by Springrbua** [comment]
@angelozerr The second point is still open, but thats nothing critical. The rest seems to work fine.

**Comment by angelozerr** [comment]
> Generating a module with routing will no longer generate an associated component.

Is that? Can we fix something? If yes, what?

**Comment by Springrbua** [comment]
It's just the preview of the generated files. It shows, that Component-files ("*.component.ts", "*.component.spec.ts", "*.component.html", "*.component.html") are generated, which is not the case anymore.  
They can simply be removed from [here](https://github.com/angelozerr/angular2-eclipse/blob/master/ts.eclipse.ide.angular2.cli/src/ts/eclipse/ide/angular2/internal/cli/wizards/NewNgModuleWizardPage.java#L78).

**Comment by angelozerr** [comment]
> They can simply be removed from here.

Ok thanks, could you remove it please. I would like to close this issue.

**Comment by Springrbua** [comment]
Yea I'll do that this noon.

**Comment by angelozerr** [comment]
Thanks!

**Comment by radhakrishnan88** [comment]
Hi,
  I used below command its works fine
`ng new my-app`
