### ISSUE TITLE
Improve use of ng

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/angular2-eclipse#52]
The preferences Javascript/Typescript/Angular2/CLI  'use ng custom file' is used to add this value in the Path env (when terminal is opened with CLI Wizard). It must be improved 

 * to select the folder where ng is stored and not the ng file.
 * display the directory of the the ng folder.
 * validate if ng file exists in the selected folder.

I think it should be cool to check the existing of the ng in the CLI wizard when a project must be generated. In the case of ng doesn't exists, execute "npm install -g angular/cli" before executing "ng new"

@Springrbua what do you think about thoses ideas?

**Comment by Springrbua** [comment]
I like your idea for selecting cusom ng-installation. For a user it's simpler to select the installation folder, then knowing the exact file. Also validating the give folder seems verry helpfull.  
We could also try to provide "nested" Angular-CLI, just like we do with TypeScript and NodeJS.  

The Wizards ("ng new" and "ng generate") could use the ng-installation set in the preferences (global, nested, custom)  to run "ng --version".  
We could then perform the following checks:  
- Does "ng"-file exists in given location?  
- Is the "ng"-version compatible with plugin-version?  

If the checks fail, we could show a warning and use the nested CLI-version instead.  
The nested CLI should then only be used for this Wizard, the preferences shouldn't be changed.  
That way we don't need to install something globally and can be sure, that there is always at least one compatible Angular-CLI installation available.

**Comment by angelozerr** [comment]
> We could also try to provide "nested" Angular-CLI, just like we do with TypeScript and NodeJS.

My fear is that angular cli changes every time.

You have understood the idea, do the same like node and typescript runtime. I think we should improve to thoses preferences for validation (ex: node location doesn't exists, etc)

**Comment by Springrbua** [comment]
> My fear is that angular cli changes every time.

Angular-CLI is now in RC, so I guess there won't be to many breaking changes.  
Also, if we ship the plugin with nested version, we always have a compatible version we can use.  
It might not be the latest available (depending on the release-cycle), but it will work with the current Plugin-version.  
Also the users can always use a local, newer version, if they wish to.  
So I don't think its a huge problem, if Angular-CLI changes often, or is it a lot of work to update the nested version?

**Comment by Springrbua** [comment]
We could add it in Wizard, but I guess usually you use the same CLI-Version for the everything in the project, so you can set it in the preferences.  
In the Wizard it will only be needed in rare cases I guess, so if we want to add it, it shouldn't be to "prominent" in the UI.  

How would you implement the 4rd option (combo with available ng)?  
Are they all embeded or will they be installed on demand? If so, where will they be installed?

**Comment by angelozerr** [comment]
> We could add it in Wizard, but I guess usually you use the same CLI-Version for the everything in the project, so you can set it in the preferences.

My idea is to provide preferences to select by default the ng. But when you want to generate a CLI project, the wizard gives the capability to select and change the ng.

> How would you implement the 4rd option (combo with available ng)?

By executing  `npm show @angular/cli versions`

> Are they all embeded or will they be installed on demand? If so, where will they be installed?

No just by executing `npm install @angular/cli@SELECTED_VERSION`

**Comment by Springrbua** [comment]
So selecting the Angular-CLI version should only be possible in the project wizard (this makes sense).  
It could then automatically set the project-specific preferences for the Angular-CLI, if selected CLI is different then workspace CLI.  

> by executing npm install @angular/cli@SELECTED_VERSION  
So it is installed inside the project right? The preferences could then be set to "custom ng" with the path to the project-specific installation.  
It would then automatically be updated, when you update CLI in project.
