### ISSUE TITLE
No way to change tab formatting.

### ISSUE THREAD

**Issue by craftyInstigator** [angelozerr/angular2-eclipse#59]
There seems to be no way to change the tab indentation to 2 spaces. No matter what the editors are set to in terms of formatting and settings in Eclipse, TypeScript editor always indents 4 spaces.

**Comment by angelozerr** [comment]
Do you use 1.2.0-SNAPSHOT? It should fix this problem. Please note formatting is customized only with TypeScript / Editor / Format preferences.

**Comment by craftyInstigator** [comment]
@angelozerr Thank you. Updating to 1.2.0-SNAPSHOT resolves the issue for me.
