### ISSUE TITLE
Local Update site for 1.2.0

### ISSUE THREAD

**Issue by mailtoab** [angelozerr/angular2-eclipse#60]
I am not able to install angular2 plugin in eclipse.

Anyone have local update site for angular2 eclipse plugin
Angular2 Eclipse 1.2.0-SNAPSHOT?

**Comment by angelozerr** [comment]
You should wait for the 1.2.0 release and after you will able to download it.

Hope the release will be done this month.

**Comment by angelozerr** [comment]
Done see https://github.com/angelozerr/angular2-eclipse/releases/tag/angular2.ide-1.2.0
