### ISSUE TITLE
npm install -g @angular/cli

### ISSUE THREAD

**Issue by mailtoab** [angelozerr/angular2-eclipse#61]
**Am using 
Window 7 64 bit, 
Node Version: v6.10.0, 
NPM Version: 3.10.10**

### While running the below command
**npm install -g @angular/cli**

I am gettiing the following error

> npm ERR! fetch failed https://registry.npmjs.org/@angular/cli/-/cli-1.0.0-rc.2.t
> gz
> npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
> s code 403
> npm ERR! fetch failed https://registry.npmjs.org/@angular/cli/-/cli-1.0.0-rc.2.t
> gz
> npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
> s code 403
> npm ERR! fetch failed https://registry.npmjs.org/@angular/cli/-/cli-1.0.0-rc.2.t
> gz
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\program files\\nodejs\\node.exe" "C:\\program files\\nodejs\\
> node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
> npm ERR! node v6.10.0
> npm ERR! npm  v3.10.10
> 
> npm ERR! fetch failed with status code 403
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Windows\system32\npm-debug.log

Can anyone help?

**Comment by angelozerr** [comment]
If you have the same problem when you open a cmd DOS, please fill your issue to angular project.

**Comment by angelozerr** [comment]
@mailtoab your problem is about using npm. Perhaps you have a proxy which causes this problem like http://stackoverflow.com/questions/34260755/npm-install-403-issue

This issue is out of the scope of angular2 eclipse. I close this issue.
