### ISSUE TITLE
angular2 project cannot be created in eclipse neon2

### ISSUE THREAD

**Issue by johnson-ajar** [angelozerr/angular2-eclipse#62]
Hi, 
I installed angular2-eclipse from the following location  http://oss.opensagres.fr/angular2-eclipse/1.2.0-SNAPSHOT/  in my eclipse neon2. 
Angular 2 Eclipse version 1.2.0.201703140726
TypeScript Core version 1.2.0.201703140717
TypeScript JSDT Integration 1.2.0.201703140717
TypeScript Validator ''''
I have trouble creating an angular2 project, when I checked the folder it doesn't contain .project file and .settings folder. 
ng new ${appName} run on my terminal view and creates the required angular2 related folders and files.

**Comment by angelozerr** [comment]
It seems that it's a bug with terminal interpreter which should create at the end of the process the .project.

Which OS do you use? 

Could you copy/paste your terminal content.

Is it possible to execute typescript.java with source to debug it?

**Comment by johnson-ajar** [comment]
The OS i am using is ubuntu 14.0, and installed JRE java-8-openjdk-amd64.
Below I have pasted the terminal output when angular-cli is run, when creating a new project. 
Unfortunately, I am not using the angular2-eclipse source to debug the issue in typescript.java.

thanks.
Johnson Abraham
PS1='\w\$ '

ng new demo2

johnson_ajar@johnson-ajar:~/dev/tutorial/spring_angular2$ PS1='\w\$ '
~/dev/tutorial/spring_angular2$ 
~/dev/tutorial/spring_angular2$ ng new demo2
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing ng2
  create .editorconfig
  create README.md
  create src/app/app.component.css
  create src/app/app.component.html
  create src/app/app.component.spec.ts
  create src/app/app.component.ts
  create src/app/environment.ts
  create src/app/index.ts
  create src/app/shared/index.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/system-config.ts
  create src/tsconfig.json
  create src/typings.d.ts
  create angular-cli-build.js
  create angular-cli.json
  create config/environment.dev.ts
  create config/environment.js
  create config/environment.prod.ts
  create config/karma-test-shim.js
  create config/karma.conf.js
  create config/protractor.conf.js
  create e2e/app.e2e-spec.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create e2e/typings.d.ts
  create .gitignore
  create package.json
  create public/.npmignore
  create tslint.json
  create typings.json
Successfully initialized git.
⠇ Installing packages for tooling via npm
├── es6-shim (ambient)
├── angular-protractor (ambient dev)
├── jasmine (ambient dev)
└── selenium-webdriver (ambient dev)

Installed packages for tooling via npm.
~/dev/tutorial/spring_angular2$

**Comment by angelozerr** [comment]
@johnson-ajar please reinstall 1.2.0-SNAPSHOT which should provide a Terminal Debug View. Please open this view and execute after the wizard. You will see traces in the Terminal View. Please add it in this issue. Thanks!

See https://github.com/angelozerr/angular2-eclipse/wiki/ngTerminal#terminal-debug fore more info

**Comment by johnson-ajar** [comment]
@angelozerr Thanks for your reply. I reinstalled the angular2-eclipse and then tried to created the angular2 project using the wizard and by running the ng new command in the terminal.
Based on the instruction in the URL on terminal-debug, running ng new  in the terminal created the angular2 files , but eclipse didn't update it as an eclipse project.
Same result using the angular2 project wizard as well. For some reason, the wizard seems to cd..  the specifed location when creating the angular2 files. 

[terminal_debug_output_after_the_wizard.txt](https://github.com/angelozerr/angular2-eclipse/files/886800/terminal_debug_output_after_the_wizard.txt)
[terminal_debug_output_using_terminal_commands.txt](https://github.com/angelozerr/angular2-eclipse/files/886801/terminal_debug_output_using_terminal_commands.txt)
please let me know if you need further information. 
thanks,
Johnson Abraham

**Comment by angelozerr** [comment]
@johnson-ajar could you redo the same traces one for wizard and one terminal but by closing terminal before and clear logs in Terminal Debug View. Thanks!

**Comment by angelozerr** [comment]
@johnson-ajar could you reinstall 1.2.0-SNAPSHOT please and tell me if it works better? Thanks!

**Comment by johnson-ajar** [comment]
@angelozerr : Sorry couldn't reply on time with the required info as per your previous request. I did re-installed angular2-eclipse 1.2.0.201704061424 and was able to create the angular2 projects and works fine.

**Comment by angelozerr** [comment]
It should work better since I have rewritten the terminal interpreter. Very good news!

Thanks for your feedback!
