### ISSUE TITLE
Install link for 1.2.0

### ISSUE THREAD

**Issue by sayantansinha** [angelozerr/angular2-eclipse#65]
Referring to issue #55, now that it is released, where is the installation link? Eclipse Marketplace still refers to Angular 2 1.1.0.

**Comment by angelozerr** [comment]
> Eclipse Marketplace still refers to Angular 2 1.1.0.

Yes it's normal, release was not done. Please be patient or install it with update site https://github.com/angelozerr/angular2-eclipse/wiki/Installation-Update-Site

**Comment by angelozerr** [comment]
Angular2 Eclipse 1.2.0 was relased and marketplace install it now.
