### ISSUE TITLE
Update AngularCLI pojos

### ISSUE THREAD

**Issue by Springrbua** [angelozerr/angular2-eclipse#66]
The pojos for the ".angular-cli.json"-Properties isn't up to date anymore.  
During the beta-phase the json changed quite a bit and therefore the pojo of this plugin needs to be updated too.  
Especially the [Defaults](https://github.com/angelozerr/angular2-eclipse/blob/master/ts.eclipse.ide.angular2.cli/src/ts/eclipse/ide/angular2/internal/cli/json/Defaults.java) have changed. The changes can be found [here](https://github.com/angular/angular-cli/wiki/stories-1.0-update#generator-defaults).

**Comment by angelozerr** [comment]
Fixed with https://github.com/angelozerr/angular2-eclipse/pull/72
