### ISSUE TITLE
Broken on Windows without a global node.js installation

### ISSUE THREAD

**Issue by rdicroce** [angelozerr/angular2-eclipse#67]
On Windows, without a global node.js installation, it's impossible to get the Angular CLI integration to work.

The CLI integration looks for a ng.cmd file. The ng.cmd that I have looks for node.exe in the working directory and uses that if it exists, otherwise it assumes node.exe is in PATH. CLIProcessHelper#getNgVersion() executes ng.cmd and fails because without a global node.js installation, node.exe doesn't exist in either place.

This should be changed so that a node.js installation can be specified. Possibly, it could use the value set in JavaScript -> TypeScript -> Node.js. Then, when executing ng.cmd, either PATH needs to be modified or the working directory needs to be set so that ng.cmd can find the desired node.exe.

**Comment by angelozerr** [comment]
This feature should b eavailable in 1.2.0-SNAPSHOT. Please install with update site https://github.com/angelozerr/angular2-eclipse/wiki/Installation-Update-Site

**Comment by rdicroce** [comment]
I'm already using 1.2.0-SNAPSHOT. Sorry, should've mentioned that.

**Comment by angelozerr** [comment]
Ok I understand more the problem now. I will check it.
