### ISSUE TITLE
eclipse with tomcat

### ISSUE THREAD

**Issue by TranscentraThiru** [angelozerr/angular2-eclipse#70]
How to run Angular 2 project through tomcat 8.0 in eclipse?

**Comment by angelozerr** [comment]
To be honnest with you, I have never try to use tomcat with Angular2 Project. ng serve provides already a server.

Any feedback are welcome, and if it needs to develop someting, please share your idea.

**Comment by Springrbua** [comment]
@TranscentraThiru The Angular-CLI Wiki provides documentation for different stories. One of them is [serving from disk](https://github.com/angular/angular-cli/wiki/stories-disk-serve), which could be what you are looking for.

**Comment by TranscentraThiru** [comment]
Thank's for the feedback and information

**Comment by Springrbua** [comment]
@TranscentraThiru please let us know if this solved your problem, so that this Issue can be closed.  
Thanks

**Comment by TranscentraThiru** [comment]
Great. It's Working. Thank you @Springrbua

**Comment by angelozerr** [comment]
Thanks @Springrbua for your help!
