### ISSUE TITLE
Editors think Modules Cannot Be Found

### ISSUE THREAD

**Issue by crgardner** [angelozerr/angular2-eclipse#73]
Just downloaded the latest snapshot of the plugin.  Created a hello angular project.  Everything seems to work.  However, editor displays errors that angular modules cannot be found:
![screenshot from 2017-04-08 15-07-05](https://cloud.githubusercontent.com/assets/2078792/24831710/213b753e-1c6d-11e7-84ce-f9b95d79f0b6.png)

**Comment by Springrbua** [comment]
If I remember it correctly, I had the same issue in other IDEs too, so I guess it is a problem with the @angular/language-service. Not sure if they fixed it now...  
I'll try to verify that asap.

**Comment by angelozerr** [comment]
This error is managed by the TypeScript tsserver. Are you sure that you have `@angular/core` module in your `node_modules`?

**Comment by crgardner** [comment]
Maybe the modules are not there. Should the tests run if the modules were missing?  I did try to manually npm install all those modules and refresh and rebuild the project, but to no avail.  I'm using Neon.3 on Fedora Linux 24.

**Comment by Springrbua** [comment]
@crgardner you still have this Issue after running "npm install"? Did you refresh the project?  
If you did, please try to run "ng serve. If that works, the modules are installed and imported correctly and the error must be somewhere else.

**Comment by angelozerr** [comment]
As I said, to check quickly, you must just open your `node_modules ` and see that:

![angularmodule](https://cloud.githubusercontent.com/assets/1932211/24869394/5bdc220e-1e13-11e7-9bda-80bce3fa93de.png)

**Comment by angelozerr** [comment]
@crgardner is your node_modules folder looks like my screenshot? Have you enable tsserver plugins?

**Comment by angelozerr** [comment]
None answer, I close this issue. @crgardner please install 1.2.0 release. If you have problems again, please reopen the issue.
