### ISSUE TITLE
Install @angular/cli with "Angular2 Project"

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/angular2-eclipse#74]
Today, before using `Angular2 Project` wizard,  you must install @angular/cli at hand like

`npm install -g @angular/cli `

It should be very cool if `Angular2 Project` wizard could provide the capability to execute (or not)

`npm install @angular/cli `

Before `ng new ${project-name}` is executed.

The challenge is to reference the `ng` command (base directory) in the Path env (I think we should update the Path env with `node_modules/.bin` before executing  `ng` (not sure with that).

@Springrbua i fyou are interested, any contribution are welcome!

**Comment by Springrbua** [comment]
I see one problem with this approach:  
If you create a new Project "Test", the Root-Folder "test" is created with the "ng new Test" command.  
However, the "ng" command should already be executed with the ng-command inside "test/node_modules".  
I did a quick test and it seems like we could create the directory immediately and Angular-CLI will automatically generate everything inside that directory.  
So we could do the following:  
1) Create Project-Folder
2) Run npm install @angular/cli (using the selected version) inside the project folder
3) Set the new angular-cli installation as the default one for this project.
3) Run ng new ${project-name} in the projects parent folder.  

What do you think about that?

**Comment by angelozerr** [comment]
Yes I think it's a good idea.

**Comment by Springrbua** [comment]
@angelozerr I guess this can be closed right?

**Comment by angelozerr** [comment]
Yes sure! Many thanks @Springrbua for your great work!
