### ISSUE TITLE
Create new project with illegal name  ==> project created in eclipse but cli fails

### ISSUE THREAD

**Issue by javaspeak** [angelozerr/angular2-eclipse#75]
This is maybe more of a feature request than bug - I do not know.

However thought I would give feedback anyway.

If you do:

    File ==> New ==> Angular 2 Project

and enter an illegal name like:

    trying_april_11

for the project name, the project will be created in eclipse but CLI in the terminal will fail.

If the person is a newbie (like me not so long ago) they may not realise that they need to open the terminal window to see the error.

Therefore the suggestion is that it would be good if the plugin opened up the terminal window view if it is not already open. That way the user would see the error if they typed in an illegal name.

This is not a problem for me as I can easily delete the eclipse project and then try again with a legal name.  However like I said "newbie" people may be confused if they see no error (because the terminal window is not open).

**Comment by angelozerr** [comment]
To do that we need to know the rule of CLI (like @Springrbua have done for preview of generated name).

@Springrbua is there any chance that you can study this issue? I think we should have a warn and not an error for that

**Comment by Springrbua** [comment]
As much as I remember Angular-IDE does that, at least for the name "test", which does not seem to be supported by the CLI for now.  
I can study what a valid name is and try to show error or warning on that. I would say, we should show error, as the CLI won't be able to create the project.  

But I guess what @javaspeak meant is, that a terminal should be openend, as the terminal shows the error. I guess, the Terminal is actually open, but in another perspective. If you are in Java.Perspective and create Angular-Project, the terminal will open there. Then it will automatically switch to Angular-Perspective, where there is no terminal.  
Is there anything we can do about that @angelozerr ?

**Comment by Springrbua** [comment]
Here is the *.ts-File, which validates the Project name: [validate-project-name.ts](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/utilities/validate-project-name.ts).  
We could study that file, to see which names are valid and which are not.

**Comment by angelozerr** [comment]
Thanks @Springrbua for the info. If you can implement the validation it should be very cool.

**Comment by Springrbua** [comment]
@angelozerr Yea, I can take a look at it.

**Comment by Springrbua** [comment]
@angelozerr @javaspeak I guess this Issue can be closed right?

**Comment by angelozerr** [comment]
I'm wiating for @javaspeak test this feature to close this issue.

**Comment by javaspeak** [comment]
@angelozerr and @Springrbua,  I just tested:  Angular2 Eclipse 1.3.0.201705030642 on a mac and I can confirm that if I use an invalid project name like "blah_stuff" it correctly gives a warning like:  

    Project name "blah_stuff" is not valid ....

I have also noticed that if the eclipse terminal is closed it now opens automatically which is good.

Thanks for the above 2 features.

A possible improvement could be to disable the "next" or "finish" buttons until the project name is valid.   If a user somehow missed the warning message they could still click "next" or "finish".  However this is just a "like to have" feature and I am not sure if it is worth your time implementing.

**Comment by angelozerr** [comment]
> A possible improvement could be to disable the "next" or "finish" buttons until the project name is valid. If a user somehow missed the warning message they could still click "next" or "finish". However this is just a "like to have" feature and I am not sure if it is worth your time implementing.

To do that, it's easy, it should replace "warning" message with "error" message. But we have done the choice to set a "warning" message to avoid blocking the use of the wizard if cli changes the rule.
