### ISSUE TITLE
Wizzard "New Module": nothing happens when clicking on "Finish"

### ISSUE THREAD

**Issue by rehbein-dieter** [angelozerr/angular2-eclipse#78]
The wizzard to create a new angular 2 module does not work. Klicking on "Finish" does nothing.
Selecting the checkbox "Flat" does not change the "Generated Files".

**Comment by angelozerr** [comment]
Have you an error in the Log View?

**Comment by rehbein-dieter** [comment]
Unfortunately not.

**Comment by angelozerr** [comment]
Please share your project

**Comment by angelozerr** [comment]
> Selecting the checkbox "Flat" does not change the "Generated Files".

is it normal?

**Comment by rehbein-dieter** [comment]
Hm, I've just created a new empty project using the "New Angular 2 Project" Wizzard and that works fine.

The project, where I'm having the problem is a project, which was NOT created by your eclipse-plugin. Unfortunately I cannot share the project (it contains code for our customer which I'm not allowed to share).

I will try to reproduce the problem without the confidential code (but this may take some time).

Thanks for the quick response!

**Comment by rehbein-dieter** [comment]
I now have a very small project, which I could share. How should I do that? (I have a zip-file with the entire project without the node-modules folder)

To reproduce (I'm using Eclipse Neon.3 with version 1.2.0 of your plugin on Windows 10):

- unzip the file
- in Eclipse:  File/Import/General/Existing Projects into Workspace 
- select the project and import it
- click the right mouse-button on the components folder (in src/app) and select new angular module
- enter a module name (e.g. TestModule) and click  "Finish" => nothing happens

**Comment by Springrbua** [comment]
@rehbein-dieter Is there anything already running in the terminal?
I had a similar problem once, when I had multiple terminals open, of which some were already running a command (for example "ng serve").  
Unfortunately I wasn't able to reproduce that.  
Please try to close all the terminals and retry to generate a Module/Component etc.

@angelozerr I just had a look at the code and saw, that there is a little bug. The "generated files" do not react on the `flat` combobox. The command, however, should be executed correctly anyways.  
To fix it you can only change [this line](https://github.com/angelozerr/angular2-eclipse/blob/master/ts.eclipse.ide.angular2.cli/src/ts/eclipse/ide/angular2/internal/cli/wizards/NewNgModuleWizardPage.java#L96) to:
`String folderName = isFlat() ? "" : cliJson.getFolderName(name);`

**Comment by rehbein-dieter** [comment]
I'v just created a new issue regarding the "Flat" checkbox (the command is missing the "--flat" option).

Regarding open terminals: yes, I have some terminals open, I'll check, if closing the terminals helps...

**Comment by Springrbua** [comment]
@angelozerr Just had another look at the code and @rehbein-dieter is right, I forgot to implement the logic for the `flat`-option.  
Sorry for that, I'll add it as soon as possible!

**Comment by angelozerr** [comment]
> Sorry for that, 

No pb @Springrbua !

> I'll add it as soon as possible!

Thanks!

**Comment by rehbein-dieter** [comment]
Regarding this issue: It seems, that I was simply too impatient. When I import the project into the workspace, I have to wait, until the javascript validation is finished (which takes some time, because the entire node-modules-folder seems to be validated). As soon as the validation is finished, the "new module" wizzard works as expected (except the flat option :-))

**Comment by Springrbua** [comment]
@rehbein-dieter good to hear that. If it happens again, please let us know!

**Comment by Springrbua** [comment]
@rehbein-dieter @angelozerr can we close this issue?
