### ISSUE TITLE
Wizzard new module: selecting checkbox "Flat" does not work

### ISSUE THREAD

**Issue by rehbein-dieter** [angelozerr/angular2-eclipse#79]
Although the checkbox "Flat" is selected, the ng generate command is executed without the "--flat" option and therefore a subfolder is created for the new module.

**Comment by Springrbua** [comment]
@rehbein-dieter thanks for pointin that out. I just had a look at the code and it seems like I forgot to add the logic to that checkbox -.-  
The flat-option for the module generation was added recently and I just added it in the wizard, without actually implementing it's logic...
