### ISSUE TITLE
Support for codelyzer/tslint

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/angular2-eclipse#8]
Support for https://github.com/mgechev/codelyzer

**Comment by micaelgallego** [comment]
I think it is better to support the whole angular-cli as backend

**Comment by angelozerr** [comment]
What do you mean with that?

I have read quickly https://scotch.io/tutorials/use-the-angular-cli-for-faster-angular-2-projects?utm_content=buffer92391&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer and it seems codelizer adds tslint rule for Angular2. 

I would like to support tslint inside typescript.java https://github.com/angelozerr/typescript.java/issues/49

**Comment by micaelgallego** [comment]
I think that it would be good if angular-cli is the default tool to manage angular 2 projects. There are a lot of seeds and generators out there, but angular-cli is the official tool and it will receive a lot of love from angular 2 team and the community. Codelyzer is included in angular-cli. It is executed with command "ng lint". 

There are more commands that can be executed from your angular2-eclipse. Maybe, you can consider angular-cli in angular2-eclipse as you consider tsserver in typescript.java. That is, a backend that execute several commands. As a first approach, commands can be write directly in a generic "angular2-cli command dialog" and its output can be printed in a special angular2 console.

What do you think?

**Comment by angelozerr** [comment]
> I think that it would be good if angular-cli is the default tool to manage angular 2 projects. 

I agree and it's in my stack. My idea is to execute some angular-cli command and do some process according the command like resresh eclipse resources, add eclipse error marker, etc

**Comment by micaelgallego** [comment]
Cool ;)

**Comment by Springrbua** [comment]
Not sure if it has something to do with this issue, but angular-cli has now a "ng lint" command.
This command Lints the code in the porject and emits wrong files, including error position and description.
Example:
```
src/app/core/core.module.ts[5, 1]: space indentation expected
src/app/core/core.module.ts[6, 1]: space indentation expected
src/app/core/core.module.ts[7, 1]: space indentation expected
src/app/core/core.module.ts[8, 1]: space indentation expected
src/app/shared/shared.module.ts[5, 1]: space indentation expected
src/app/shared/shared.module.ts[6, 1]: space indentation expected
src/app/shared/shared.module.ts[7, 1]: space indentation expected
src/app/shared/shared.module.ts[8, 1]: space indentation expected
```

The ng-lint command also supports following options:
--fix will attempt to fix lint errors
--force will always return error code 0 even with lint errors
--format the output formatter to use

It might be possible to consume this command for linting and providing fixes?

**Comment by angelozerr** [comment]
codelyzer is working now since tslint is now integrated with https://github.com/angelozerr/tslint-language-service
