### ISSUE TITLE
HTML intellisense disappears

### ISSUE THREAD

**Issue by JoeF24** [angelozerr/angular2-eclipse#85]
I installed a fresh copy for Eclipse for web developers. Opened and .html file and had intellisense for html tags (i.e. `<div> <p>` etc.). I then installed angularj2 support and when I open .html files I nolonger have intellisense for html tags.   If you need more information please let me know.

**Comment by angelozerr** [comment]
It should work, have you this config:

![image](https://cloud.githubusercontent.com/assets/1932211/26615731/7e069476-45c9-11e7-9a07-a17b6741ba70.png)

Please attach a sreenshot with completion which doesn't work.

**Comment by angelozerr** [comment]
@JoeF24 please give me more info. Thanks!

**Comment by angelozerr** [comment]
Noen answer, I close this issue. Please reopen it if you have again the problem.
