### ISSUE TITLE
Html editor shows errors on some image assets

### ISSUE THREAD

**Issue by cvgaviao** [angelozerr/angular2-eclipse#88]
When we create a component using "ng g c" it creates a folder inside "<project>/app" and html file inside that created folder.
If our images are in the folder <project>/assets/img, then I use this in order to angular understand it:
`<img src="assets/img/flags/USA.png" alt="USA" style="height:24px;">`

But the Html editor shows me an error and its completion shows me a file at "../../assets/img/flags/USA.png"

**Comment by angelozerr** [comment]
I think you have installed https://github.com/angelozerr/eclipse-wtp-webresources

I close this issue since it's not linked to Angular2 Eclipse. This feature will be available when @angular/language-service will support it and I will finish my integration of @angular/language-service inside HTML.
