### ISSUE TITLE
Install 1.2.0 and 1.30-Snapshot aren't working

### ISSUE THREAD

**Issue by mikerieser** [angelozerr/angular2-eclipse#89]
I've just downloaded the latest Eclipse JEE Neon (3) 64-bit on Windows 10. I get the following error when attempting to install. (Note I was able to install 1.1.0 successfully.)

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://oss.opensagres.fr/angular2-eclipse/1.2.0/plugins/ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64_1.2.0.201704141415.jar.
Premature end of Content-Length delimited message body (expected: 10753044; received: 130801
Unable to read repository at http://oss.opensagres.fr/angular2-eclipse/1.2.0/plugins/ts.repository_1.2.0.201704141415.jar.
Premature end of Content-Length delimited message body (expected: 14769365; received: 130801

**Comment by tuxtor** [comment]
I hat the same issue yesterday, however today I was able to install the snapshot version plugin over eclipse Neon. Networking issue in the server maybe?

**Comment by mikerieser** [comment]
Thanks! I've been trying each day since I opened this issue. Today it now works!

**Comment by angelozerr** [comment]
Please note that you have a local update site at https://github.com/angelozerr/angular2-eclipse/releases (only for releases).

The server used to host update site is free, so it can ba have some trouble. I close this issue since it's a problem with Networking.
