### ISSUE TITLE
Angular 2 eclipse ide issue

### ISSUE THREAD

**Issue by hemantmali21** [angelozerr/angular2-eclipse#91]
Hi Angelo,
   I have installed Angular 2 ide plugin in eclipse.
Following steps I followed:
1. Eclipse market place
2.Search Angular 2
3.Then installed angular 1.2.0 snapshot.
4 Select file menu in eclipse and select new project in that I selected Angular 2 project.It just gets freezed. 
5 .But it doesn't creat project.

I am not getting any errors.
I am using Eclipse neon 2 and OS is cent os

**Comment by angelozerr** [comment]
Please install eclipse angular2 1.3.0 snapshot which improve a lot the wizard to create angular project https://github.com/angelozerr/angular2-eclipse/wiki/Installation-Update-Site and tell me if it fixes your problem.

**Comment by hemantmali21** [comment]
my issue resolved.thanks.you can close the ticket.
