### ISSUE TITLE
No npm executable

### ISSUE THREAD

**Issue by ruben-suarez-treelogic** [angelozerr/angular2-eclipse#92]
Just installed from _http://oss.opensagres.fr/angular2-eclipse/1.3.0-SNAPSHOT/_ (same issue installing from _http://oss.opensagres.fr/angular2-eclipse/1.2.0/_ ) on Ubuntu Linux 17.04.
Configured to use **Embedded node.js** (node-v6.9.4-linux-x64).
Then create a new Angular Project.  Seems that the project is created Ok, but no **node_modules** created.
I think that the problem is unpacking _plugins/ts.eclipse.ide.server.nodejs.embed.linux.gtk.x86_64_1.3.0.201707061117/node-v6.9.4-linux-x64.tar.gz_ on _workspace/.metadata/.plugins/ts.eclipse.ide.server.nodejs.embed.linux.gtk.x86_64_ as _node-v6.9.4-linux-x64/bin/npm_ is created as regular file with **0 byte size** (not a link to _../lib/node_modules/npm/bin/npm_)

**Comment by angelozerr** [comment]
Thanks @ruben-suarez-treelogic for your information. It seems that  `workspace/.metadata/.plugins/ts.eclipse.ide.server.nodejs.embed.linux.gtk.x86_64 as node-v6.9.4-linux-x64/bin/npm` is a symbol link to the `node-v6.9.4-linux-x86_64\lib\node_modules\npm\bin` file.

I have tried to support symbolink link with https://github.com/angelozerr/typescript.java/commit/ac71192dc760de0d00f4797b8a1081df8fede182

I cannot test because I'm on Windows OS and in this case npm from windows node zip has not symbol link.

Please reinstall 1.3.0-SNAPSHOT and tell it fixes your problem. Thanks.

If it doesn't work, please help me by creating a simple main wich consumes https://github.com/angelozerr/typescript.java/blob/master/core/ts.core/src/ts/utils/ZipUtils.java (extractTar)

Thanks!

**Comment by ruben-suarez-treelogic** [comment]
Hello @angelozerr 

Sorry but fix doesn't work.
Just done a clean installation from _http://oss.opensagres.fr/angular2-eclipse/1.3.0-SNAPSHOT/_ 
Now **node-v6.9.4-linux-x64.tar.gz** is not extracted in _workspace/.metadata/.plugins/ts.eclipse.ide.server.nodejs.embed.linux.gtk.x86_64_ and is not available to select in _Preferences --> JavaScript --> TypeScript --> Node.js_

**NOTE**:  Now is worst than before.  Before, I could fix the installation by simple remove **npm** (0 byte file) and making a new **symlink** to _../lib/node_modules/npm/bin/npm_.  Now I must extract myself full **node-v6.9.4-linux-x64.tar.gz** to make that available (and restart Eclipse so change is detected).

**NOTE2**:  Made a simple Java test with main class.  This is the "no so good" test code:

`import java.io.File;
import java.io.IOException;

import ts.utils.ZipUtils;

public class ZipUtilsTest {

	public static void main(String[] args) throws IOException {
		File tarFile = new File("/tmp/node-v6.9.4-linux-x64.tar.gz");
		File destPath = new File("/tmp/extracted/");
		ZipUtils.extractTar(tarFile, destPath);
	}

}`

And the exception thrown (causing the file not to be extracted):

`Exception in thread "main" java.nio.file.NoSuchFileException: /tmp/extracted/node-v6.9.4-linux-x64/bin/npm
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createSymbolicLink(UnixFileSystemProvider.java:457)
	at java.nio.file.Files.createSymbolicLink(Files.java:1043)
	at ts.utils.ZipUtils.extractTar(ZipUtils.java:181)
	at ZipUtilsTest.main(ZipUtilsTest.java:11)
`

**Comment by angelozerr** [comment]
> NOTE: Now is worst than before. 

Yes it's normal, I have not catched error when symbolink link crashes.

> NOTE2: Made a simple Java test with main class. This is the "no so good" test code:

It's exactly that I would like you do. I think error comes from https://github.com/angelozerr/typescript.java/blob/master/core/ts.core/src/ts/utils/ZipUtils.java#L180

It should really cool if you could fix it. Thanks!

**Comment by angelozerr** [comment]
Could you test with:

`Path symTarget = new File(entry.getLinkName()).toPath();`

**Comment by rubensa** [comment]
Hello @angelozerr 

I'm @ruben-suarez-treelogic but using my personal (not corporate) github account.

I think that found and fixed the problem (create parent directories before create the link, just like doing for regular files).

I've created a new pull request https://github.com/angelozerr/typescript.java/pull/188

Whit this code change, the test code just worked fine.
