### ISSUE TITLE
Weird character on npm Script execution

### ISSUE THREAD

**Issue by rubensa** [angelozerr/angular2-eclipse#96]
Right click on _package.json -- build --> Run as --> npm Script_  results in oppening a **Console** (not a **Terminal**) with lot of "unreadable"  characters (cause process status percentage?)

\> prueba@0.0.0 build /home/rubensa/development/eclipse/4.7.0_base/workspace/prueba
\> ng build

  0% compiling 10% building modules 0/1 modules 1 active ...7.0_base/workspace/prueba/src/main.ts                                          10% building modules 1/1 modules 0 active 10% building modules 1/2 modules 1 active ...ase/workspace/prueba/src/polyfills.ts                                          10% building modules 2/2 modules 0 active 10% building modules 2/3 modules 1 active ..._base/workspace/prueba/src/styles.css                                          10% building modules 3/3 modules 0 active 10% building modules 3/4 modules 1 active ..._base/workspace/prueba/src/styles.css                                          10% building modules 4/4 modules 0 active 10% building modules 4/5 modules 1 active ..._base/workspace/prueba/src/styles.css 10% building modules 4/6 modules 2 active ...7.0_base/workspace/prueba/src/main.ts 10% building modules 4/7 modules 3 active ...ase/workspace/prueba/src/polyfills.ts 10% building modules 5/7 modules 2 active ...ase/workspace/prueba/src/polyfills.ts 10% building modules 6/7 modules 1 active ..._base/workspace/prueba/src/styles.css 10% building modules 6/8 modules 2 active ...ode_modules/style-loader/addStyles.js 10% building modules 6/9 modules 3 active ...orkspace/prueba/src/app/app.module.ts 10% building modules 7/9 modules 2 active ...ode_modules/style-loader/addStyles.js 10% building modules 7/10 modules 3 active ...rueba/src/environments/environment.ts 10% building modules 8/10 modules 2 active ...ode_modules/style-loader/addStyles.js 10% building modules 8/11 modules 3 active ...es/@angular/core/@angular/core.es5.js 10% building modules 8/12 modules 4 active ...gular/platform-browser-dynamic.es5.js 11% building modules 9/12 modules 3 active ...gular/platform-browser-dynamic.es5.js 11% building modules 10/12 modules 2 active ...gular/platform-browser-dynamic.es5.js 11% building modules 10/13 modules 3 active ...space/prueba/src/app/app.component.ts 11% building modules 11/13 modules 2 active ...gular/platform-browser-dynamic.es5.js 11% building modules 11/14 modules 3 active ...wser/@angular/platform-browser.es5.js 11% building modules 11/15 modules 4 active ...de_modules/css-loader/lib/css-base.js 11% building modules 11/16 modules 5 active ...ace/prueba/src/app/app.component.html 11% building modules 11/17 modules 6 active ...a/node_modules/core-js/es6/reflect.js 11% building modules 11/18 modules 7 active ...a/node_modules/core-js/es7/reflect.js 11% building modules 11/19 modules 8 active ...eba/node_modules/zone.js/dist/zone.js 11% building modules 12/19 modules 7 active ...eba/node_modules/zone.js/dist/zone.js 11% building modules 13/19 modules 6 active ...eba/node_modules/zone.js/dist/zone.js 11% building modules 13/20 modules 7 active ...4.7.0_base/workspace/prueba/src async 11% building modules 14/20 modules 6 active ...eba/node_modules/zone.js/dist/zone.js 11% building modules 15/20 modules 5 active ...eba/node_modules/zone.js/dist/zone.js 11% building modules 15/21 modules 6 active ...lar/compiler/@angular/compiler.es5.js 11% building modules 15/22 modules 7 active ...angular/common/@angular/common.es5.js 11% building modules 16/22 modules 6 active ...angular/common/@angular/common.es5.js 12% building modules 17/22 modules 5 active ...angular/common/@angular/common.es5.js 12% building modules 18/22 modules 4 active ...angular/common/@angular/common.es5.js 12% building modules 19/22 modules 3 active ...angular/common/@angular/common.es5.js 12% building modules 20/22 modules 2 active ...angular/common/@angular/common.es5.js 12% building modules 20/23 modules 3 active ...rueba/node_modules/rxjs/Observable.js 12% building modules 20/24 modules 4 active ...e/prueba/node_modules/rxjs/Subject.js 12% building modules 20/25 modules 5 active ...node_modules/rxjs/observable/merge.js 12% building modules 20/26 modules 6 active ...a/node_modules/rxjs/operator/share.js 12% building modules 20/27 modules 7 active ...pace/prueba/src/app/app.component.css 12% building modules 20/28 modules 8 active .../core-js/modules/es6.reflect.apply.js 12% building modules 20/29 modules 9 active ...e-js/modules/es6.reflect.construct.js 12% building modules 20/30 modules 10 active ...odules/es6.reflect.define-property.js 12% building modules 20/31 modules 11 active ...odules/es6.reflect.delete-property.js 12% building modules 20/32 modules 12 active ...e-js/modules/es6.reflect.enumerate.js 12% building modules 20/33 modules 13 active ...es/core-js/modules/es6.reflect.get.js 12% building modules 20/34 modules 14 active ...eflect.get-own-property-descriptor.js 12% building modules 20/35 modules 15 active ...dules/es6.reflect.get-prototype-of.js 12% building modules 20/36 modules 16 active ...es/core-js/modules/es6.reflect.has.js 12% building modules 20/37 modules 17 active .../modules/es6.reflect.is-extensible.js 12% building modules 20/38 modules 18 active ...re-js/modules/es6.reflect.own-keys.js 12% building modules 20/39 modules 19 active ...les/es6.reflect.prevent-extensions.js 12% building modules 20/40 modules 20 active ...es/core-js/modules/es6.reflect.set.js 12% building modules 20/41 modules 21 active ...dules/es6.reflect.set-prototype-of.js 12% building modules 20/42 modules 22 active ...node_modules/core-js/modules/_core.js 12% building modules 20/43 modules 23 active ...odules/es7.reflect.define-metadata.js 12% building modules 20/44 modules 24 active ...odules/es7.reflect.delete-metadata.js 12% building modules 20/45 modules 25 active ...s/modules/es7.reflect.get-metadata.js 12% building modules 20/46 modules 26 active ...ules/es7.reflect.get-metadata-keys.js 12% building modules 20/47 modules 27 active ...dules/es7.reflect.get-own-metadata.js 12% building modules 20/48 modules 28 active .../es7.reflect.get-own-metadata-keys.js 12% building modules 20/49 modules 29 active ...s/modules/es7.reflect.has-metadata.js 12% building modules 20/50 modules 30 active ...dules/es7.reflect.has-own-metadata.js 12% building modules 20/51 modules 31 active ...re-js/modules/es7.reflect.metadata.js 12% building modules 20/52 modules 32 active ...rueba/node_modules/tslib/tslib.es6.js 12% building modules 20/53 modules 33 active ...ode_modules/webpack/buildin/global.js 12% building modules 21/53 modules 32 active ...ode_modules/webpack/buildin/global.js 12% building modules 22/53 modules 31 active ...ode_modules/webpack/buildin/global.js 12% building modules 23/53 modules 30 active ...ode_modules/webpack/buildin/global.js 12% building modules 24/53 modules 29 active ...ode_modules/webpack/buildin/global.js 13% building modules 25/53 modules 28 active ...ode_modules/webpack/buildin/global.js 13% building modules 26/53 modules 27 active ...ode_modules/webpack/buildin/global.js 13% building modules 27/53 modules 26 active ...ode_modules/webpack/buildin/global.js 13% building modules 28/53 modules 25 active ...ode_modules/webpack/buildin/global.js 13% building modules 29/53 modules 24 active ...ode_modules/webpack/buildin/global.js 13% building modules 30/53 modules 23 active ...ode_modules/webpack/buildin/global.js 13% building modules 31/53 modules 22 active ...ode_modules/webpack/buildin/global.js 13% building modules 32/53 modules 21 active ...ode_modules/webpack/buildin/global.js 13% building modules 33/53 modules 20 active ...ode_modules/webpack/buildin/global.js 14% building modules 34/53 modules 19 active ...ode_modules/webpack/buildin/global.js 14% building modules 35/53 modules 18 active ...ode_modules/webpack/buildin/global.js 14% building modules 36/53 modules 17 active ...ode_modules/webpack/buildin/global.js 14% building modules 37/53 modules 16 active ...ode_modules/webpack/buildin/global.js 14% building modules 38/53 modules 15 active ...ode_modules/webpack/buildin/global.js 14% building modules 39/53 modules 14 active ...ode_modules/webpack/buildin/global.js 14% building modules 40/53 modules 13 active ...ode_modules/webpack/buildin/global.js 14% building modules 41/53 modules 12 active ...ode_modules/webpack/buildin/global.js 15% building modules 42/53 modules 11 active ...ode_modules/webpack/buildin/global.js 15% building modules 43/53 modules 10 active ...ode_modules/webpack/buildin/global.js  15% building modules 44/53 modules 9 active ...ode_modules/webpack/buildin/global.js 15% building modules 45/53 modules 8 active ...ode_modules/webpack/buildin/global.js 15% building modules 46/53 modules 7 active ...ode_modules/webpack/buildin/global.js 15% building modules 47/53 modules 6 active ...ode_modules/webpack/buildin/global.js 15% building modules 48/53 modules 5 active ...ode_modules/webpack/buildin/global.js 15% building modules 49/53 modules 4 active ...ode_modules/webpack/buildin/global.js 16% building modules 50/53 modules 3 active ...ode_modules/webpack/buildin/global.js 16% building modules 51/53 modules 2 active ...ode_modules/webpack/buildin/global.js 16% building modules 52/53 modules 1 active ...ode_modules/webpack/buildin/global.js                                          16% building modules 53/53 modules 0 active 16% building modules 53/54 modules 1 active ...rueba/node_modules/rxjs/Subscriber.js 16% building modules 53/55 modules 2 active ...eba/node_modules/rxjs/Subscription.js 16% building modules 53/56 modules 3 active ...e_modules/rxjs/SubjectSubscription.js 16% building modules 53/57 modules 4 active ...a/node_modules/rxjs/operator/merge.js 16% building modules 53/58 modules 5 active ...de_modules/rxjs/operator/multicast.js 16% building modules 53/59 modules 6 active ...de_modules/core-js/modules/_export.js 16% building modules 53/60 modules 7 active ...odules/core-js/modules/_a-function.js 16% building modules 53/61 modules 8 active ...modules/core-js/modules/_an-object.js 16% building modules 53/62 modules 9 active ...de_modules/core-js/modules/_global.js 16% building modules 53/63 modules 10 active ...ode_modules/core-js/modules/_fails.js 16% building modules 53/64 modules 11 active ...les/core-js/modules/_object-create.js 16% building modules 53/65 modules 12 active ...modules/core-js/modules/_is-object.js 16% building modules 53/66 modules 13 active ...node_modules/core-js/modules/_bind.js 16% building modules 53/67 modules 14 active ...modules/core-js/modules/_object-dp.js 16% building modules 53/68 modules 15 active ...ules/core-js/modules/_to-primitive.js 16% building modules 53/69 modules 16 active ...dules/core-js/modules/_iter-create.js 16% building modules 53/70 modules 17 active ...dules/core-js/modules/_object-gopd.js 16% building modules 53/71 modules 18 active ...odules/core-js/modules/_object-gpo.js 16% building modules 53/72 modules 19 active .../node_modules/core-js/modules/_has.js 16% building modules 53/73 modules 20 active ..._modules/core-js/modules/_own-keys.js 16% building modules 53/74 modules 21 active ...les/core-js/modules/_property-desc.js 16% building modules 53/75 modules 22 active ...modules/core-js/modules/_set-proto.js 16% building modules 53/76 modules 23 active ..._modules/core-js/modules/_metadata.js 16% building modules 53/77 modules 24 active ...de_modules/core-js/modules/es6.set.js 16% building modules 53/78 modules 25 active ...re-js/modules/_array-from-iterable.js 16% building modules 53/79 modules 26 active ...prueba/node_modules/rxjs/util/root.js 16% building modules 53/80 modules 27 active ...ode_modules/rxjs/util/toSubscriber.js 16% building modules 53/81 modules 28 active .../rxjs/util/ObjectUnsubscribedError.js 16% building modules 53/82 modules 29 active ...ode_modules/rxjs/symbol/observable.js 16% building modules 53/83 modules 30 active ...e_modules/rxjs/symbol/rxSubscriber.js 16% building modules 54/83 modules 29 active ...e_modules/rxjs/symbol/rxSubscriber.js 16% building modules 55/83 modules 28 active ...e_modules/rxjs/symbol/rxSubscriber.js 16% building modules 56/83 modules 27 active ...e_modules/rxjs/symbol/rxSubscriber.js 16% building modules 57/83 modules 26 active ...e_modules/rxjs/symbol/rxSubscriber.js 16% building modules 58/83 modules 25 active ...e_modules/rxjs/symbol/rxSubscriber.js 17% building modules 59/83 modules 24 active ...e_modules/rxjs/symbol/rxSubscriber.js 17% building modules 60/83 modules 23 active ...e_modules/rxjs/symbol/rxSubscriber.js 17% building modules 61/83 modules 22 active ...e_modules/rxjs/symbol/rxSubscriber.js 17% building modules 62/83 modules 21 active ...e_modules/rxjs/symbol/rxSubscriber.js 17% building modules 63/83 modules 20 active ...e_modules/rxjs/symbol/rxSubscriber.js 17% building modules 64/83 modules 19 active ...e_modules/rxjs/symbol/rxSubscriber.js 17% building modules 65/83 modules 18 active ...e_modules/rxjs/symbol/rxSubscriber.js 17% building modules 66/83 modules 17 active ...e_modules/rxjs/symbol/rxSubscriber.js 18% building modules 67/83 modules 16 active ...e_modules/rxjs/symbol/rxSubscriber.js 18% building modules 68/83 modules 15 active ...e_modules/rxjs/symbol/rxSubscriber.js 18% building modules 69/83 modules 14 active ...e_modules/rxjs/symbol/rxSubscriber.js 18% building modules 70/83 modules 13 active ...e_modules/rxjs/symbol/rxSubscriber.js 18% building modules 71/83 modules 12 active ...e_modules/rxjs/symbol/rxSubscriber.js 18% building modules 72/83 modules 11 active ...e_modules/rxjs/symbol/rxSubscriber.js 18% building modules 73/83 modules 10 active ...e_modules/rxjs/symbol/rxSubscriber.js  18% building modules 74/83 modules 9 active ...e_modules/rxjs/symbol/rxSubscriber.js 19% building modules 75/83 modules 8 active ...e_modules/rxjs/symbol/rxSubscriber.js 19% building modules 76/83 modules 7 active ...e_modules/rxjs/symbol/rxSubscriber.js 19% building modules 77/83 modules 6 active ...e_modules/rxjs/symbol/rxSubscriber.js 19% building modules 78/83 modules 5 active ...e_modules/rxjs/symbol/rxSubscriber.js 19% building modules 79/83 modules 4 active ...e_modules/rxjs/symbol/rxSubscriber.js 19% building modules 80/83 modules 3 active ...e_modules/rxjs/symbol/rxSubscriber.js 19% building modules 81/83 modules 2 active ...e_modules/rxjs/symbol/rxSubscriber.js 19% building modules 82/83 modules 1 active ...e_modules/rxjs/symbol/rxSubscriber.js                                          19% building modules 83/83 modules 0 active 19% building modules 83/84 modules 1 active .../node_modules/rxjs/util/isFunction.js 19% building modules 83/85 modules 2 active .../prueba/node_modules/rxjs/Observer.js 19% building modules 83/86 modules 3 active ...eba/node_modules/rxjs/util/isArray.js 19% building modules 83/87 modules 4 active ...ba/node_modules/rxjs/util/isObject.js 19% building modules 83/88 modules 5 active ...ba/node_modules/rxjs/util/tryCatch.js 19% building modules 83/89 modules 6 active ...node_modules/rxjs/util/errorObject.js 19% building modules 83/90 modules 7 active ...ules/rxjs/util/UnsubscriptionError.js 19% building modules 83/91 modules 8 active ...s/observable/ConnectableObservable.js 19% building modules 83/92 modules 9 active ...es/rxjs/observable/ArrayObservable.js 19% building modules 83/93 modules 10 active ...ode_modules/rxjs/operator/mergeAll.js 19% building modules 83/94 modules 11 active ...node_modules/rxjs/util/isScheduler.js 19% building modules 83/95 modules 12 active ...node_modules/core-js/modules/_hide.js 19% building modules 83/96 modules 13 active ..._modules/core-js/modules/_redefine.js 19% building modules 83/97 modules 14 active .../node_modules/core-js/modules/_ctx.js 19% building modules 83/98 modules 15 active ...odules/core-js/modules/_object-dps.js 19% building modules 83/99 modules 16 active ...les/core-js/modules/_enum-bug-keys.js 19% building modules 83/100 modules 17 active ...odules/core-js/modules/_shared-key.js 19% building modules 83/101 modules 18 active ...odules/core-js/modules/_dom-create.js 19% building modules 83/102 modules 19 active ...node_modules/core-js/modules/_html.js 19% building modules 83/103 modules 20 active ...de_modules/core-js/modules/_invoke.js 19% building modules 83/104 modules 21 active ...es/core-js/modules/_ie8-dom-define.js 19% building modules 83/105 modules 22 active ...dules/core-js/modules/_descriptors.js 19% building modules 83/106 modules 23 active ...core-js/modules/_set-to-string-tag.js 19% building modules 83/107 modules 24 active .../node_modules/core-js/modules/_wks.js 19% building modules 83/108 modules 25 active ...odules/core-js/modules/_object-pie.js 19% building modules 83/109 modules 26 active ...odules/core-js/modules/_to-iobject.js 19% building modules 83/110 modules 27 active ...modules/core-js/modules/_to-object.js 19% building modules 83/111 modules 28 active ...dules/core-js/modules/_object-gopn.js 19% building modules 83/112 modules 29 active ...dules/core-js/modules/_object-gops.js 19% building modules 83/113 modules 30 active ...de_modules/core-js/modules/es6.map.js 19% building modules 83/114 modules 31 active ...de_modules/core-js/modules/_shared.js 19% building modules 83/115 modules 32 active ...dules/core-js/modules/es6.weak-map.js 19% building modules 83/116 modules 33 active ...core-js/modules/_collection-strong.js 19% building modules 83/117 modules 34 active ...odules/core-js/modules/_collection.js 19% building modules 83/118 modules 35 active ...de_modules/core-js/modules/_for-of.js 20% building modules 84/118 modules 34 active ...de_modules/core-js/modules/_for-of.js 20% building modules 85/118 modules 33 active ...de_modules/core-js/modules/_for-of.js 20% building modules 86/118 modules 32 active ...de_modules/core-js/modules/_for-of.js 20% building modules 87/118 modules 31 active ...de_modules/core-js/modules/_for-of.js 20% building modules 88/118 modules 30 active ...de_modules/core-js/modules/_for-of.js 20% building modules 89/118 modules 29 active ...de_modules/core-js/modules/_for-of.js 20% building modules 90/118 modules 28 active ...de_modules/core-js/modules/_for-of.js 20% building modules 91/118 modules 27 active ...de_modules/core-js/modules/_for-of.js 21% building modules 92/118 modules 26 active ...de_modules/core-js/modules/_for-of.js 21% building modules 93/118 modules 25 active ...de_modules/core-js/modules/_for-of.js 21% building modules 94/118 modules 24 active ...de_modules/core-js/modules/_for-of.js 21% building modules 95/118 modules 23 active ...de_modules/core-js/modules/_for-of.js 21% building modules 96/118 modules 22 active ...de_modules/core-js/modules/_for-of.js 21% building modules 97/118 modules 21 active ...de_modules/core-js/modules/_for-of.js 21% building modules 98/118 modules 20 active ...de_modules/core-js/modules/_for-of.js 21% building modules 99/118 modules 19 active ...de_modules/core-js/modules/_for-of.js 22% building modules 100/118 modules 18 active ...de_modules/core-js/modules/_for-of.js 22% building modules 101/118 modules 17 active ...de_modules/core-js/modules/_for-of.js 22% building modules 102/118 modules 16 active ...de_modules/core-js/modules/_for-of.js 22% building modules 103/118 modules 15 active ...de_modules/core-js/modules/_for-of.js 22% building modules 104/118 modules 14 active ...de_modules/core-js/modules/_for-of.js 22% building modules 105/118 modules 13 active ...de_modules/core-js/modules/_for-of.js 22% building modules 106/118 modules 12 active ...de_modules/core-js/modules/_for-of.js 22% building modules 107/118 modules 11 active ...de_modules/core-js/modules/_for-of.js 22% building modules 108/118 modules 10 active ...de_modules/core-js/modules/_for-of.js  23% building modules 109/118 modules 9 active ...de_modules/core-js/modules/_for-of.js 23% building modules 110/118 modules 8 active ...de_modules/core-js/modules/_for-of.js 23% building modules 111/118 modules 7 active ...de_modules/core-js/modules/_for-of.js 23% building modules 112/118 modules 6 active ...de_modules/core-js/modules/_for-of.js 23% building modules 113/118 modules 5 active ...de_modules/core-js/modules/_for-of.js 23% building modules 114/118 modules 4 active ...de_modules/core-js/modules/_for-of.js 23% building modules 115/118 modules 3 active ...de_modules/core-js/modules/_for-of.js 23% building modules 116/118 modules 2 active ...de_modules/core-js/modules/_for-of.js 24% building modules 117/118 modules 1 active ...de_modules/core-js/modules/_for-of.js                                          24% building modules 118/118 modules 0 active 24% building modules 118/119 modules 1 active ...s/rxjs/observable/ScalarObservable.js 24% building modules 118/120 modules 2 active ...es/rxjs/observable/EmptyObservable.js 24% building modules 118/121 modules 3 active .../node_modules/rxjs/OuterSubscriber.js 24% building modules 118/122 modules 4 active ...odules/rxjs/util/subscribeToResult.js 24% building modules 118/123 modules 5 active .../node_modules/core-js/modules/_uid.js 24% building modules 118/124 modules 6 active ...dules/core-js/modules/_object-keys.js 24% building modules 118/125 modules 7 active ...e_modules/core-js/modules/_iobject.js 24% building modules 118/126 modules 8 active ...e_modules/core-js/modules/_defined.js 24% building modules 118/127 modules 9 active ...e-js/modules/_object-keys-internal.js 24% building modules 118/128 modules 10 active ...les/core-js/modules/_array-methods.js 24% building modules 118/129 modules 11 active ...node_modules/core-js/modules/_meta.js 24% building modules 118/130 modules 12 active ...les/core-js/modules/_object-assign.js 24% building modules 118/131 modules 13 active ...s/core-js/modules/_collection-weak.js 24% building modules 118/132 modules 14 active ...ules/core-js/modules/_redefine-all.js 24% building modules 118/133 modules 15 active ...dules/core-js/modules/_an-instance.js 24% building modules 118/134 modules 16 active ...dules/core-js/modules/_iter-detect.js 24% building modules 118/135 modules 17 active ...re-js/modules/_inherit-if-required.js 24% building modules 118/136 modules 18 active ...dules/core-js/modules/_iter-define.js 24% building modules 118/137 modules 19 active ...modules/core-js/modules/_iter-step.js 24% building modules 118/138 modules 20 active ...dules/core-js/modules/_set-species.js 24% building modules 118/139 modules 21 active ...modules/core-js/modules/_iter-call.js 24% building modules 118/140 modules 22 active ...les/core-js/modules/_is-array-iter.js 24% building modules 118/141 modules 23 active ...modules/core-js/modules/_to-length.js 24% building modules 118/142 modules 24 active ...s/modules/core.get-iterator-method.js 24% building modules 119/142 modules 23 active ...s/modules/core.get-iterator-method.js 24% building modules 120/142 modules 22 active ...s/modules/core.get-iterator-method.js 24% building modules 121/142 modules 21 active ...s/modules/core.get-iterator-method.js 24% building modules 122/142 modules 20 active ...s/modules/core.get-iterator-method.js 24% building modules 123/142 modules 19 active ...s/modules/core.get-iterator-method.js 24% building modules 124/142 modules 18 active ...s/modules/core.get-iterator-method.js 25% building modules 125/142 modules 17 active ...s/modules/core.get-iterator-method.js 25% building modules 126/142 modules 16 active ...s/modules/core.get-iterator-method.js 25% building modules 127/142 modules 15 active ...s/modules/core.get-iterator-method.js 25% building modules 128/142 modules 14 active ...s/modules/core.get-iterator-method.js 25% building modules 129/142 modules 13 active ...s/modules/core.get-iterator-method.js 25% building modules 130/142 modules 12 active ...s/modules/core.get-iterator-method.js 25% building modules 131/142 modules 11 active ...s/modules/core.get-iterator-method.js 25% building modules 132/142 modules 10 active ...s/modules/core.get-iterator-method.js  25% building modules 133/142 modules 9 active ...s/modules/core.get-iterator-method.js 26% building modules 134/142 modules 8 active ...s/modules/core.get-iterator-method.js 26% building modules 135/142 modules 7 active ...s/modules/core.get-iterator-method.js 26% building modules 136/142 modules 6 active ...s/modules/core.get-iterator-method.js 26% building modules 137/142 modules 5 active ...s/modules/core.get-iterator-method.js 26% building modules 138/142 modules 4 active ...s/modules/core.get-iterator-method.js 26% building modules 139/142 modules 3 active ...s/modules/core.get-iterator-method.js 26% building modules 140/142 modules 2 active ...s/modules/core.get-iterator-method.js 26% building modules 141/142 modules 1 active ...modules/core-js/modules/_to-length.js                                          27% building modules 142/142 modules 0 active 27% building modules 142/143 modules 1 active ...node_modules/rxjs/util/isArrayLike.js 27% building modules 142/144 modules 2 active ...a/node_modules/rxjs/util/isPromise.js 27% building modules 142/145 modules 3 active .../node_modules/rxjs/symbol/iterator.js 27% building modules 142/146 modules 4 active .../node_modules/rxjs/InnerSubscriber.js 27% building modules 142/147 modules 5 active .../node_modules/core-js/modules/_cof.js 27% building modules 142/148 modules 6 active ...es/core-js/modules/_array-includes.js 27% building modules 142/149 modules 7 active ...e-js/modules/_array-species-create.js 27% building modules 142/150 modules 8 active ...e_modules/core-js/modules/_library.js 27% building modules 142/151 modules 9 active ...modules/core-js/modules/_iterators.js 27% building modules 142/152 modules 10 active ...e_modules/core-js/modules/_classof.js 27% building modules 142/153 modules 11 active ...odules/core-js/modules/_to-integer.js 27% building modules 143/153 modules 10 active ...odules/core-js/modules/_to-integer.js  27% building modules 144/153 modules 9 active ...odules/core-js/modules/_to-integer.js 27% building modules 145/153 modules 8 active ...odules/core-js/modules/_to-integer.js 27% building modules 146/153 modules 7 active ...odules/core-js/modules/_to-integer.js 27% building modules 147/153 modules 6 active ...odules/core-js/modules/_to-integer.js 27% building modules 148/153 modules 5 active ...odules/core-js/modules/_to-integer.js 27% building modules 149/153 modules 4 active ...odules/core-js/modules/_to-integer.js 28% building modules 150/153 modules 3 active ...odules/core-js/modules/_to-integer.js 28% building modules 151/153 modules 2 active ...odules/core-js/modules/_to-integer.js 28% building modules 152/153 modules 1 active ...odules/core-js/modules/_to-integer.js                                          28% building modules 153/153 modules 0 active 28% building modules 153/154 modules 1 active ..._modules/core-js/modules/_to-index.js 28% building modules 153/155 modules 2 active ...modules/_array-species-constructor.js 28% building modules 154/155 modules 1 active ...modules/_array-species-constructor.js                                          28% building modules 155/155 modules 0 active 28% building modules 155/156 modules 1 active ..._modules/core-js/modules/_is-array.js                                          28% building modules 156/156 modules 0 active                                   71% sealing 72% optimizing 73% basic module optimization       74% module optimization 75% advanced module optimization     76% basic chunk optimization 76% basic chunk optimization pass 2 76% basic chunk optimization pass 3 76% basic chunk optimization pass 4              77% chunk optimization 78% advanced chunk optimization 79% module and chunk tree optimization                    80% module reviving 81% module order optimization    82% module id optimization         83% chunk reviving 84% chunk order optimization    85% chunk id optimization               86% hashing 87% module assets processing  88% chunk assets processing 89% additional chunk assets processing                          90% recording 91% additional asset processing    92% chunk asset optimization       94% asset optimization           95% emitting             Hash: [1m4e3815d0774547289186[39m[22m
Time: [1m6241[39m[22mms
chunk    {[1m[33m0[39m[22m} [1m[32mpolyfills.bundle.js, polyfills.bundle.js.map[39m[22m (polyfills) 160 kB {[1m[33m4[39m[22m}[1m[33m [initial][39m[22m[1m[32m [rendered][39m[22m
chunk    {[1m[33m1[39m[22m} [1m[32mmain.bundle.js, main.bundle.js.map[39m[22m (main) 5.27 kB {[1m[33m3[39m[22m}[1m[33m [initial][39m[22m[1m[32m [rendered][39m[22m
chunk    {[1m[33m2[39m[22m} [1m[32mstyles.bundle.js, styles.bundle.js.map[39m[22m (styles) 10.5 kB {[1m[33m4[39m[22m}[1m[33m [initial][39m[22m[1m[32m [rendered][39m[22m
chunk    {[1m[33m3[39m[22m} [1m[32mvendor.bundle.js, vendor.bundle.js.map[39m[22m (vendor) 1.88 MB[1m[33m [initial][39m[22m[1m[32m [rendered][39m[22m
chunk    {[1m[33m4[39m[22m} [1m[32minline.bundle.js, inline.bundle.js.map[39m[22m (inline) 0 bytes[1m[33m [entry][39m[22m[1m[32m [rendered][39m[22m

I think that execution should be done on **Terminal** (instead of **Console**) or fix "someway" the output.

**Comment by angelozerr** [comment]
Totally agree with you:) But it's an issue of Eclipse JSDT and not an issue of Angular2 Eclipse.
